:- module('database_Roma.pl', [matchSA/5]).
matchSA("Salernitana", "Roma", "AWAY_TEAM", 0, 1).
matchSA("Roma", "Cremonese", "HOME_TEAM", 1, 0).
matchSA("Juventus", "Roma", "DRAW", 1, 1).
matchSA("Roma", "Monza", "HOME_TEAM", 3, 0).
matchSA("Udinese", "Roma", "HOME_TEAM", 4, 0).
matchSA("Empoli", "Roma", "AWAY_TEAM", 1, 2).
matchSA("Roma", "Atalanta", "AWAY_TEAM", 0, 1).
matchSA("Inter", "Roma", "AWAY_TEAM", 1, 2).
matchSA("Roma", "Lecce", "HOME_TEAM", 2, 1).
matchSA("Sampdoria", "Roma", "AWAY_TEAM", 0, 1).
matchSA("Roma", "Napoli", "AWAY_TEAM", 0, 1).
matchSA("Verona", "Roma", "AWAY_TEAM", 1, 3).
matchSA("Roma", "Lazio", "AWAY_TEAM", 0, 1).
matchSA("Sassuolo", "Roma", "DRAW", 1, 1).
matchSA("Roma", "Torino", "DRAW", 1, 1).
matchSA("Roma", "Bologna", "HOME_TEAM", 1, 0).
matchSA("Milan", "Roma", "DRAW", 2, 2).
matchSA("Roma", "Fiorentina", "HOME_TEAM", 2, 0).
matchSA("Spezia Calcio", "Roma", "AWAY_TEAM", 0, 2).
matchSA("Napoli", "Roma", "HOME_TEAM", 2, 1).
matchSA("Roma", "Empoli", "HOME_TEAM", 2, 0).
matchSA("Lecce", "Roma", null, null, null).
matchSA("Roma", "Verona", null, null, null).
matchSA("Cremonese", "Roma", null, null, null).
matchSA("Roma", "Juventus", null, null, null).
matchSA("Roma", "Sassuolo", null, null, null).
matchSA("Lazio", "Roma", null, null, null).
matchSA("Roma", "Sampdoria", null, null, null).
matchSA("Torino", "Roma", null, null, null).
matchSA("Roma", "Udinese", null, null, null).
matchSA("Atalanta", "Roma", null, null, null).
matchSA("Roma", "Milan", null, null, null).
matchSA("Monza", "Roma", null, null, null).
matchSA("Roma", "Inter", null, null, null).
matchSA("Bologna", "Roma", null, null, null).
matchSA("Roma", "Salernitana", null, null, null).
matchSA("Fiorentina", "Roma", null, null, null).
matchSA("Roma", "Spezia Calcio", null, null, null).
