:- module('database_Udinese.pl', [matchSA/5]).
matchSA("Milan", "Udinese", "HOME_TEAM", 4, 2).
matchSA("Udinese", "Salernitana", "DRAW", 0, 0).
matchSA("Monza", "Udinese", "AWAY_TEAM", 1, 2).
matchSA("Udinese", "Fiorentina", "HOME_TEAM", 1, 0).
matchSA("Udinese", "Roma", "HOME_TEAM", 4, 0).
matchSA("Sassuolo", "Udinese", "AWAY_TEAM", 1, 3).
matchSA("Udinese", "Inter", "HOME_TEAM", 3, 1).
matchSA("Verona", "Udinese", "AWAY_TEAM", 1, 2).
matchSA("Udinese", "Atalanta", "DRAW", 2, 2).
matchSA("Lazio", "Udinese", "DRAW", 0, 0).
matchSA("Udinese", "Torino", "AWAY_TEAM", 1, 2).
matchSA("Cremonese", "Udinese", "DRAW", 0, 0).
matchSA("Udinese", "Lecce", "DRAW", 1, 1).
matchSA("Spezia Calcio", "Udinese", "DRAW", 1, 1).
matchSA("Napoli", "Udinese", "HOME_TEAM", 3, 2).
matchSA("Udinese", "Empoli", "DRAW", 1, 1).
matchSA("Juventus", "Udinese", "HOME_TEAM", 1, 0).
matchSA("Udinese", "Bologna", "AWAY_TEAM", 1, 2).
matchSA("Sampdoria", "Udinese", "AWAY_TEAM", 0, 1).
matchSA("Udinese", "Verona", "DRAW", 1, 1).
matchSA("Torino", "Udinese", "HOME_TEAM", 1, 0).
matchSA("Udinese", "Sassuolo", null, null, null).
matchSA("Inter", "Udinese", null, null, null).
matchSA("Udinese", "Spezia Calcio", null, null, null).
matchSA("Atalanta", "Udinese", null, null, null).
matchSA("Empoli", "Udinese", null, null, null).
matchSA("Udinese", "Milan", null, null, null).
matchSA("Bologna", "Udinese", null, null, null).
matchSA("Udinese", "Monza", null, null, null).
matchSA("Roma", "Udinese", null, null, null).
matchSA("Udinese", "Cremonese", null, null, null).
matchSA("Lecce", "Udinese", null, null, null).
matchSA("Udinese", "Napoli", null, null, null).
matchSA("Udinese", "Sampdoria", null, null, null).
matchSA("Fiorentina", "Udinese", null, null, null).
matchSA("Udinese", "Lazio", null, null, null).
matchSA("Salernitana", "Udinese", null, null, null).
matchSA("Udinese", "Juventus", null, null, null).
