:- module('database_Spezia Calcio.pl', [matchSA/5]).
:- multifile(matchSA/5).
matchSA("Spezia Calcio", "Empoli", "HOME_TEAM", 1, 0).
matchSA("Inter", "Spezia Calcio", "HOME_TEAM", 3, 0).
matchSA("Spezia Calcio", "Sassuolo", "DRAW", 2, 2).
matchSA("Juventus", "Spezia Calcio", "HOME_TEAM", 2, 0).
matchSA("Spezia Calcio", "Bologna", "DRAW", 2, 2).
matchSA("Napoli", "Spezia Calcio", "HOME_TEAM", 1, 0).
matchSA("Spezia Calcio", "Sampdoria", "HOME_TEAM", 2, 1).
matchSA("Lazio", "Spezia Calcio", "HOME_TEAM", 4, 0).
matchSA("Monza", "Spezia Calcio", "HOME_TEAM", 2, 0).
matchSA("Spezia Calcio", "Cremonese", "DRAW", 2, 2).
matchSA("Salernitana", "Spezia Calcio", "HOME_TEAM", 1, 0).
matchSA("Spezia Calcio", "Fiorentina", "AWAY_TEAM", 1, 2).
matchSA("Milan", "Spezia Calcio", "HOME_TEAM", 2, 1).
matchSA("Spezia Calcio", "Udinese", "DRAW", 1, 1).
matchSA("Verona", "Spezia Calcio", "AWAY_TEAM", 1, 2).
matchSA("Spezia Calcio", "Atalanta", "DRAW", 2, 2).
matchSA("Spezia Calcio", "Lecce", "DRAW", 0, 0).
matchSA("Torino", "Spezia Calcio", "AWAY_TEAM", 0, 1).
matchSA("Spezia Calcio", "Roma", "AWAY_TEAM", 0, 2).
matchSA("Bologna", "Spezia Calcio", "HOME_TEAM", 2, 0).
matchSA("Spezia Calcio", "Napoli", "AWAY_TEAM", 0, 3).
matchSA("Empoli", "Spezia Calcio", null, null, null).
matchSA("Spezia Calcio", "Juventus", null, null, null).
matchSA("Udinese", "Spezia Calcio", null, null, null).
matchSA("Spezia Calcio", "Verona", null, null, null).
matchSA("Spezia Calcio", "Inter", null, null, null).
matchSA("Sassuolo", "Spezia Calcio", null, null, null).
matchSA("Spezia Calcio", "Salernitana", null, null, null).
matchSA("Fiorentina", "Spezia Calcio", null, null, null).
matchSA("Spezia Calcio", "Lazio", null, null, null).
matchSA("Sampdoria", "Spezia Calcio", null, null, null).
matchSA("Spezia Calcio", "Monza", null, null, null).
matchSA("Atalanta", "Spezia Calcio", null, null, null).
matchSA("Cremonese", "Spezia Calcio", null, null, null).
matchSA("Spezia Calcio", "Milan", null, null, null).
matchSA("Lecce", "Spezia Calcio", null, null, null).
matchSA("Spezia Calcio", "Torino", null, null, null).
matchSA("Roma", "Spezia Calcio", null, null, null).
